# Generated by Django 4.2.23 on 2025-07-23 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.PositiveSmallIntegerField(choices=[(1, 'Baisakh'), (2, 'Jestha'), (3, 'Ashadh'), (4, 'Shrawan'), (5, 'Bhadra'), (6, 'Ashwin'), (7, 'Kartik'), (8, 'Mangsir'), (9, 'Poush'), (10, 'Magh'), (11, 'Falgun'), (12, 'Chaitra')])),
                ('billing_year', models.IntegerField(default=2082)),
                ('previous_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units_consumed', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('rate_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('bill_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rentee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.rentee')),
            ],
            options={
                'ordering': ['-billing_month'],
                'unique_together': {('rentee', 'billing_month', 'billing_year')},
            },
        ),
    ]
