# Generated by Django 4.2.23 on 2025-07-22 16:05

from django.db import migrations
import nepali_datetime_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitybill',
            name='billing_month',
            field=nepali_datetime_field.models.NepaliDateField(),
        ),
    ]
