version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - sqlite_data:/code/db_data    # Mount the db directory
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=${ALLOW_HOST}
      - SECRET_KEY=${DJANGO_SECRET_KEY}

volumes:
  sqlite_data:
